version: '3.0'
services:
  php:
    image: faqqcn/php-swoole-sdebug:1.0
    stdin_open: true
    tty: true
    ports:
      - 8080:9501
    volumes:
      - D:/www:/mnt/d/htdocs
    environment:
      - PHP_IDE_CONFIG=serverName=XDEBUG_02

  mysql:
    image: mysql:5.7.31
    ports:
      - 3306:3306
    volumes:
      - D:/www/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  redis:
    container_name: redis
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "123456"]
    volumes:
      - D:/www/redis/data:/data
    ports:
      - 6379:6379
